"""Inventory every registration in a pinned upstream checkout without importing it."""

import argparse
import ast
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "00fcc6e7f95a002c85464f0dfd193396bd7d86d3"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def inventory(source):
    source = Path(source)
    revision = subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
    if revision != COMMIT:
        raise ValueError("check out the pinned Plaso revision first")
    entries, data_types, hashes = [], set(), {}
    for path in sorted((source / "plaso/parsers").rglob("*.py")):
        relative = path.relative_to(source).as_posix()
        hashes[relative] = digest(path)
        tree = ast.parse(path.read_text(encoding="utf-8"))
        classes = {}
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            fields = {}
            for item in node.body:
                if (
                    isinstance(item, ast.Assign)
                    and len(item.targets) == 1
                    and isinstance(item.targets[0], ast.Name)
                ):
                    try:
                        fields[item.targets[0].id] = ast.literal_eval(item.value)
                    except (ValueError, TypeError):
                        pass
            classes[node.name] = fields
            if isinstance(fields.get("DATA_TYPE"), str):
                data_types.add(fields["DATA_TYPE"])
        for node in tree.body:
            if not isinstance(node, ast.Expr) or not isinstance(node.value, ast.Call):
                continue
            call = node.value
            if not isinstance(call.func, ast.Attribute) or call.func.attr not in {
                "RegisterParser",
                "RegisterParsers",
                "RegisterPlugin",
                "RegisterPlugins",
            }:
                continue
            args = call.args
            if call.func.attr.endswith("s"):
                if len(args) != 1 or not isinstance(args[0], (ast.List, ast.Tuple)):
                    raise ValueError("unresolved upstream registration")
                args = args[0].elts
            for arg in args:
                if not isinstance(arg, ast.Name) or arg.id not in classes:
                    raise ValueError("unresolved upstream registered class")
                fields = classes[arg.id]
                name = fields["NAME"]
                kind = "plugin" if "Plugin" in call.func.attr else "parser"
                parent = path.parent.name.removesuffix("_plugins") if kind == "plugin" else None
                entries.append(
                    {
                        "id": f"{parent}/{name}" if parent else name,
                        "name": name,
                        "parent": parent,
                        "kind": "cookie_plugin" if parent == "cookie" else kind,
                        "data_format": fields.get("DATA_FORMAT", fields.get("DESCRIPTION", name)),
                        "class_name": arg.id,
                        "source": relative,
                    }
                )
    ids = [e["id"] for e in entries]
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate upstream registration")
    return {
        "version": "1.0",
        "upstream_version": "20260720",
        "upstream_commit": COMMIT,
        "upstream_url": "https://github.com/log2timeline/plaso",
        "release_commit": "4ea03ef9a48dad5284c371ac9b537a184b3eea9c",
        "base_image": "log2timeline/plaso@sha256:a8d42e64dcd3af2dffed8ddb25d34f34def69b672eec97ea9af62885c9332950",
        "source_archive_sha256": "6fb3d63469b0b112b56ad08249bd344b48b4268b75b51fd122a35037f9f0e0c5",
        "entries": sorted(entries, key=lambda e: e["id"]),
        "data_types": sorted(data_types),
        "source_hashes": hashes,
        "coverage_route": "pinned_plaso_backend_to_plaso_event_importer",
    }


def coverage_markdown(value):
    lines = [
        "# Complete pinned Plaso parser inventory",
        "",
        "Generated by `scripts/build_plaso_catalog.py` from upstream registration calls.",
        "",
        "Source: [log2timeline/plaso at "
        + value["upstream_commit"][:12]
        + "](https://github.com/log2timeline/plaso/tree/"
        + value["upstream_commit"]
        + ").",
        "All rows execute through the pinned native backend and the `plaso_event` importer. Cookie plugins are helpers invoked by cookie parsers, not independent artifact selectors. See [setup, evidence rules and test scope](PLASO.md).",
        "",
        "| Registered ID | Kind | Upstream artifact format | Source |",
        "| --- | --- | --- | --- |",
    ]
    for entry in value["entries"]:
        description = str(entry["data_format"]).replace("|", "\\|").replace("\n", " ")
        link = (
            "https://github.com/log2timeline/plaso/blob/" + value["upstream_commit"] + "/" + entry["source"]
        )
        lines.append(f"| `{entry['id']}` | {entry['kind']} | {description} | [code]({link}) |")
    lines += [
        "",
        "The machine-readable [catalog](../src/timeline_demo/resources/plaso_catalog.json) also records 285 data type strings declared in parser source and hashes for every parser Python file. Shared container classes can supply additional event types; import is not restricted to this list.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("checkout")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    value = inventory(args.checkout)
    target = ROOT / "src/timeline_demo/resources/plaso_catalog.json"
    text = json.dumps(value, indent=2, ensure_ascii=False) + "\n"
    markdown = ROOT / "docs/PLASO_COVERAGE.md"
    documentation = coverage_markdown(value)
    if args.check:
        if (
            target.read_text(encoding="utf-8") != text
            or markdown.read_text(encoding="utf-8") != documentation
        ):
            raise SystemExit("Plaso catalog differs from the pinned source")
    else:
        target.write_text(text, encoding="utf-8")
        markdown.write_text(documentation, encoding="utf-8")
    print(json.dumps({"registrations": len(value["entries"]), "data_types": len(value["data_types"])}))


if __name__ == "__main__":
    main()
